app:
  port: 3000
  txAggregationTime: 2000 # milliseconds. Aggregate all incoming tx within 2 seconds into the same block

network:
  etherscan_prefix: ''
  rpc: 'http://127.0.0.1:8545'
  contract: '0x04f4D781Ba5F29603595a8f23c7E9aA00FBF3F86'

mnemonic: 'salute grocery glass box cloth pull wedding measure bright tilt shield over'
