app:
  port: 3000
  txAggregationTime: 2000 # milliseconds. Aggregate all incoming tx within 2 seconds into the same block

network:
  etherscan_prefix: 'https://rinkeby.etherscan.io/'
  rpc: 'https://rinkeby.infura.io/v3/826fec4cbd954dfd89c714eabf4611c4'
  contract: '0x489bd1f7CBb7809b6d770B8FB58cfA945ec5704Bs'

mnemonic: 'music tired panel defense garlic tomorrow feature person december lab keen sausage tourist remember era'