app:
  port: 3000
  txAggregationTime: 2000 # milliseconds. Aggregate all incoming tx within 2 seconds into the same block
  maxBatchCapacity: 30

network:
  etherscan_prefix: 'https://rinkeby.etherscan.io/'
  rpc: 'https://rinkeby.infura.io/v3/826fec4cbd954dfd89c714eabf4611c4'
  gasRpc: 'https://kovan.infura.io/v3/826fec4cbd954dfd89c714eabf4611c4'
  contract: '0x08734d27E29f82C31CC6C141f0b879E45D7398d0'
  gas_contract: '0x3af56f17caBdF0c5e882FE1377eE8B21Ea751A5A'

mnemonic: 'music tired panel defense garlic tomorrow feature person december lab keen sausage tourist remember era'
gas_mnemonic: 'music tired panel defense garlic tomorrow feature person december lab keen sausage tourist remember era'
